### PR TITLE
Funnelcakes for Yahoo search test

### PR DESCRIPTION
**Pull request by mkaply**
@ccooper I assume that there are no funnelcakes active right now right?

Does this look OK for our new Yahoo funnelcake test?

I archived everything we had and created three new ones.

### CODE REVIEW

**Comment by mkaply** [comment]
@mixedpuppy This is ready for review.

I'll be doing three more funnelcakes for the addon.

**Comment by mixedpuppy** [comment]
Lets get rid of the "old" archiving, no real sense in doing that.  We should just "git tag 63" or something like that going into the future.

**Comment by mkaply** [comment]
So then just delete them instead after tagging?

**Comment by mixedpuppy** [comment]
Yep, just get rid of them.

**Pull request closed without merging**
