### PR TITLE
Bug 1202083, configs for funnelcake 50, 51, 52 - testing firstrun experience

### PR DESCRIPTION
**Pull request by FrancescoSTL**
@nthomas-mozilla / @mixedpuppy r?

I think I did this all correctly. Let me know if there are any changes that need to be made!

### CODE REVIEW

**Comment by nthomas-mozilla** [comment]
I would suggest not setting startup.homepage_override_url, that's for the update case and I'm pretty sure the update server will either suppress or override it anyway. Similarly, I'd leave out browser.startup.homepage because that's the default value.

For 51, why do you set startup.homepage_welcome_url="about:blank" instead of "" ? It seems like it'll open a blank page (next to about:home), which is suboptimal UX.

If you're not aware, you can test these configs by creating <install_directory>/distribution/ and dropping the distribution.ini in it. Then start firefox with the profile manager and create a new profile. Mac is a bit different, but that that should work for windows & linux.

**Comment by mixedpuppy** [comment]
@nthomas in a recent partner config I found empty strings defined in distribution.ini would not override the default prefs.  Using "about:blank" fixed that, it is specifically handled in nsBrowserContentHandler.js and results in no tab being opened, so long as there is a defined homepage.  If both homepage and the welcome page are "about:blank" then the user will get a blank tab.

**Comment by nthomas-mozilla** [comment]
mixedpuppy, sounds like you are better placed to review this code. I stand by the comments about startup.homepage_override_url - even if the update server doesn't intervene, the pref is undefined in vanilla builds and we don't want to show any particular content to these users.

**Comment by mixedpuppy** [comment]
I was just responding on the about:blank override in my last comment, but I'll take a stab...

@FrancescoSTL 
ISTM that both browser.startup.homepage and startup.homepage_override_url are unnecessary in these configs.  I also wonder if startup.homepage_welcome_url in #52 shouldn't have "?f=52".  Last, seems these configs are in the "old" directory.  They instead need to be in a "desktop" directory to get built.

**Comment by FrancescoSTL** [comment]
@mixedpuppy I've now removed the .homepage_override_url and .homepage_welcome_url settings, along with adding a query string to the firstrun url in funnelcake 52, and moved all three funnelcakes to the /desktop folder. Let me know if you see any other issues!

**Pull request merged**
