### PR TITLE
Bug 1304738, configs for fc89 & 90

### PR DESCRIPTION
**Pull request by nthomas-mozilla**

### CODE REVIEW

**Comment by mkaply** [comment]
Just an FYI (I learned this the hard way). If you set a whatsnew URL in the config, the user will always get a whatsnew URL for every upgrade from now on even when we don't want them to see it. Basically you're ceding control of that whatsnew away from balrog over to distribution.ini. Also, won't startup.homepage_welcome_url.additional="about:blank" cause a second blank URL to appear on every upgrade?

**Comment by nthomas-mozilla** [comment]
These are what passed QA testing for funnelcake 87, so what do you want to do @chrismore ?

**Comment by nthomas-mozilla** [comment]
For the first issue do you must mean the startup.homepage_override_url pref, which I'd forgotten is empty now in non-funnelcake builds (ie http://hg.mozilla.org/releases/mozilla-release/file/2d931a5eaf8a/browser/branding/official/pref/firefox-branding.js#l5). The flip side is that if we want to use a whatsnew we have to special case every separate funnelcake build in Balrog, or they don't get one. Pick a poison.

re the second, I think putting startup.homepage_welcome_url.additional="about:blank" means we get to
http://hg.mozilla.org/releases/mozilla-release/file/2d931a5eaf8a/browser/components/nsBrowserContentHandler.js#l557 and fail the != "about:blank" test.

**Comment by mkaply** [comment]
First point. Yeah, you're right. And we need the upgrade information for funnelcakes. Ship it.

And for two, I forgot they check about:blank as well. I thought it has to be "".

You're good to go. Sorry for the interruption.

**Pull request merged**
